// Code generated by goagen v1.1.0, DO NOT EDIT.
//
// API "eventory": Application User Types
//
// Command:
// $ goagen
// --design=github.com/tikasan/eventory/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty

package client
