package design

import (
	"github.com/goadesign/gorma"
	. "github.com/goadesign/gorma/dsl"
)

var _ = StorageGroup("eventory", func() {
	Description("eventory Model")
	Store("MySQL", gorma.MySQL, func() {
		Description("MySQLのリレーションナルデータベース")
		Model("Event", func() {
			RendersTo(Event)
			Description("イベント")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("api_type", gorma.String)
			Field("title", gorma.String)
			Field("description", gorma.String)
			Field("identifier", gorma.String)
			Field("url", gorma.String)
			Field("limits", gorma.Integer)
			Field("data_hash", gorma.String)
			Field("accept", gorma.Integer)
			Field("wait", gorma.Integer)
			Field("address", gorma.String)
			Field("start_at", gorma.Timestamp)
			Field("end_at", gorma.Timestamp)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			HasMany("EventGenres", "EventGenre")
			HasMany("UserFollowEvents", "UserFollowEvent")
			BelongsTo("Pref")
		})
		Model("Pref", func() {
			RendersTo(Pref)
			Description("都道府県")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("name", gorma.String)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			HasMany("Events", "Event")
			HasMany("UserFollowPrefs", "UserFollowPref")
		})
		Model("Genre", func() {
			RendersTo(Genre)
			Description("ジャンル")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("name", gorma.String)
			Field("keyword", gorma.String)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			HasMany("EventGenres", "EventGenre")
			HasMany("UserFollowGenres", "UserFollowGenre")
		})
		Model("User", func() {
			Description("ユーザー")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("name", gorma.String)
			Field("email", gorma.String)
			Field("password_hash", gorma.String)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			HasMany("UserFollowGenres", "UserFollowGenre")
			HasMany("UserFollowPrefs", "UserFollowPref")
			HasMany("UserTerminals", "UserTerminal")
			HasMany("UserFollowEvents", "UserFollowEvent")
		})
		Model("EventGenre", func() {
			Description("イベントジャンル")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("genre_id", gorma.Integer)
			Field("event_id", gorma.Integer)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			BelongsTo("Event")
			BelongsTo("Genres")
		})
		Model("UserFollowGenre", func() {
			Description("ユーザーのフォロージャンル")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("user_id", gorma.Integer)
			Field("genre_id", gorma.Integer)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			BelongsTo("User")
			BelongsTo("Genre")
		})
		Model("UserFollowPref", func() {
			Description("ユーザーのフォロー都道府県")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("user_id", gorma.Integer)
			Field("pref_id", gorma.Integer)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			BelongsTo("Pref")
			BelongsTo("User")
		})
		Model("UserFollowEvent", func() {
			Description("ユーザーのキープ状態")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("user_id", gorma.Integer)
			Field("event_id", gorma.Integer)
			Field("status", gorma.String)
			Field("batch_processed", gorma.Boolean)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			BelongsTo("Event")
			BelongsTo("User")
		})
		Model("UserTerminal", func() {
			Description("ユーザーの端末情報")
			Field("id", gorma.Integer, func() {
				PrimaryKey()
			})
			Field("user_id", gorma.Integer)
			Field("platform", gorma.String)
			Field("client_version", gorma.String)
			Field("token", gorma.String)
			Field("identifier", gorma.String)
			Field("created_at", gorma.Timestamp)
			Field("updated_at", gorma.Timestamp)
			Field("deleted_at", gorma.NullableTimestamp)
			BelongsTo("User")
		})
	})
})
