// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/tikasan/eventory/design
// --out=$(GOPATH)
// --version=v1.1.0-dirty
//
// API "eventory": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"time"

	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"golang.org/x/net/context"
)

// ユーザーの端末情報
type UserTerminal struct {
	ID            int `gorm:"primary_key"` // primary key
	ClientVersion string
	Identifier    string
	Platform      string
	Token         string
	UserID        int        // Belongs To User
	CreatedAt     time.Time  // timestamp
	DeletedAt     *time.Time // nullable timestamp (soft delete)
	UpdatedAt     time.Time  // timestamp
	User          User
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m UserTerminal) TableName() string {
	return "user_terminals"

}

// UserTerminalDB is the implementation of the storage interface for
// UserTerminal.
type UserTerminalDB struct {
	Db *gorm.DB
}

// NewUserTerminalDB creates a new storage type.
func NewUserTerminalDB(db *gorm.DB) *UserTerminalDB {
	return &UserTerminalDB{Db: db}
}

// DB returns the underlying database.
func (m *UserTerminalDB) DB() interface{} {
	return m.Db
}

// UserTerminalStorage represents the storage interface.
type UserTerminalStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*UserTerminal, error)
	Get(ctx context.Context, id int) (*UserTerminal, error)
	Add(ctx context.Context, userterminal *UserTerminal) error
	Update(ctx context.Context, userterminal *UserTerminal) error
	Delete(ctx context.Context, id int) error
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *UserTerminalDB) TableName() string {
	return "user_terminals"

}

// Belongs To Relationships

// UserTerminalFilterByUser is a gorm filter for a Belongs To relationship.
func UserTerminalFilterByUser(userID int, originaldb *gorm.DB) func(db *gorm.DB) *gorm.DB {

	if userID > 0 {

		return func(db *gorm.DB) *gorm.DB {
			return db.Where("user_id = ?", userID)

		}
	}
	return func(db *gorm.DB) *gorm.DB { return db }
}

// CRUD Functions

// Get returns a single UserTerminal as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *UserTerminalDB) Get(ctx context.Context, id int) (*UserTerminal, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "get"}, time.Now())

	var native UserTerminal
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

func (m *UserTerminalDB) GetByToken(ctx context.Context, token string) (*UserTerminal, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "get"}, time.Now())

	var native UserTerminal
	err := m.Db.Table(m.TableName()).Where("token = ?", token).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

func (m *UserTerminalDB) GetByIdentifier(ctx context.Context, identifier string) (*UserTerminal, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "get userID By Identifier"}, time.Now())

	var native UserTerminal
	err := m.Db.Table(m.TableName()).Where("identifier = ?", identifier).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}
	return &native, err
}

func (m *UserTerminalDB) GetUserIDByToken(ctx context.Context, token string) (int, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "get userID By token"}, time.Now())

	var native UserTerminal
	err := m.Db.Table(m.TableName()).Where("token = ?", token).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return 0, err
	}
	return native.UserID, err
}

// List returns an array of UserTerminal
func (m *UserTerminalDB) List(ctx context.Context) ([]*UserTerminal, error) {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "list"}, time.Now())

	var objs []*UserTerminal
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *UserTerminalDB) Add(ctx context.Context, model *UserTerminal) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding UserTerminal", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *UserTerminalDB) Update(ctx context.Context, model *UserTerminal) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating UserTerminal", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *UserTerminalDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "userTerminal", "delete"}, time.Now())

	var obj UserTerminal

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting UserTerminal", "error", err.Error())
		return err
	}

	return nil
}
